server:
  port: 8888

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: productServiceRoute
          predicates:
            - Path=/products/**
          uri: http://server1:8081
          filters:
            - AddResponseHeader=X-RESPONSE-HEADER, ProductServiceRSP Header
        - id: inventoryServiceRoute
          predicates:
            - Path=/api/inventory/**
          uri: http://server2:8085
          filters:
            - AddResponseHeader=X-RESPONSE-HEADER, InventoryServiceRSP Header
    discovery:
      locator:
        lower-case-service-id: true

#eureka:
  #client:
    #service-url:
      #defaultZone: http://localhost:8083/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enable: false